config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :line_items, only: :create

  resources :carts

  get 'store/index', as: :store

  resources :products

  root 'store#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def expired_time
    time = DateTime.now.to_time - updated_at.to_time
    time /= 60**2
    destroy! if time >= 24
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart.expired_time
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: @cart.id.to_s,
               layout: 'layouts/application.pdf.erb',
               show_as_html: params[:debug].present?
      end
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_url, notice: "Tu carrito ahora esta vacio" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end

    def invalid_cart
      logger.error "Se intento acceder a un carrito invalido #{params[:id]}"
      redirect_to store_url, notice: "Carrito invalido"
    end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @cart %> |
<%= link_to 'Regresar', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Mostrar', cart %></td>
        <td><%= link_to 'Editar', edit_cart_path(cart) %></td>
        <td><%= link_to 'Eliminar', cart, method: :delete, data: { confirm: 'Está seguro que desea eliminar el producto?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>Nuevo Producto</h1>

<%= render 'form' %>

app/views/carts/show.html.erb
<section class="productos">
  <%= link_to 'Imprimir', "#{@cart.id}.pdf" %>
  <h2>Mi carrito</h2>
  <% @cart.line_items.each do |item| %>
    <article class="producto">
      <%= image_tag(item.product.image_url) %>
      <h3><%= item.quantity %> x <%= item.product.title %></h3>
      <p><%= item.product.description %></p>
      <span><%= number_to_currency(item.total_price) %></span>
    </article>
  <% end %>
  <h3 class="total">Total:</h3>
  <span><%= number_to_currency(@cart.total_price) %></span>
  <%= button_to "Limpiar carrito", @cart, method: :delete, data: { confirm: "Esta seguro que desea limpiar el carrito?" } %>
</section>

app/views/carts/show.pdf.erb
<section class="productos">
  <h2>Mi carrito</h2>
  <% @cart.line_items.each do |item| %>
    <article class="producto">
      <h3><%= item.quantity %> x <%= item.product.title %></h3>
      <p><%= item.product.description %></p>
      <span><%= number_to_currency(item.total_price) %></span>
    </article>
  <% end %>
  <h3 class="total">Total:</h3>
  <span><%= number_to_currency(@cart.total_price) %></span>
</section>